### ISSUE TITLE
Is this package working?

### ISSUE THREAD

**Issue by RacerDelux** [Lachee/unity-named-pipes#1]
It shows build failing and there are no instructions on how to actually use the package. Just curious if it is fully functional, or still in development phase?

**Comment by Lachee** [comment]
Its fully functional and is actually being used in https://github.com/Lachee/discord-rpc-csharp for the Unity Package. The build is failing and there is no usage scripts because I haven't gotten around to updating the buildscript yet or writing documentation.

**Comment by Lachee** [comment]
Build scripts have been properly updated
