### ISSUE TITLE
Pipes works in Editor, but not in Build

### ISSUE THREAD

**Issue by TheSabotender** [Lachee/unity-named-pipes#5]
I'm using NamedPipes to tell Streamlabs OBS to change scene, thanks to this dll, i got it working in the Unity Editor, but it doesnt work when I make my build. Is there something that needs to be changed in my project settings?
(I have already set Api Compatibility Level to .NET 4.x, but that is  the only thing i have changed)

**Comment by Lachee** [comment]
What version of unity are you using?

**Comment by TheSabotender** [comment]
Unity 2020.1.10f1

**Comment by TheSabotender** [comment]
Aha, I had to change the Architecture to x86_64 in the build settings, please include this in the README.md :)

**Comment by Lachee** [comment]
ah yes, I only bothered building 64bit versions of the native library. I should mention that, thanks.
